### PR TITLE
Step-1 Andrei: Create Payment Entity

### PR DESCRIPTION
**Pull request by AndreSelv**

### CODE REVIEW

**Review by MehmetKaldirim — APPROVED** [review]

**Review by MehmetKaldirim — APPROVED** [review]

**Comment by VitalySlabada** [comment]
Please add data in data sql for testing and TODO for the person in commented lines

**Review by MehmetKaldirim — APPROVED** [review]
Great job , executed properly...Maybe we can make mont enums , since they are constants...

**Comment by VitalySlabada** [comment]
Still need to do TODO for Gulmira
I agree about months, with Mehmet.

**Comment by AndreSelv** [comment]
We do not have any SRS docs for month Enum

**Review by VitalySlabada — APPROVED** [review]
Looks good! I tested yesterday

**Review by MehmetKaldirim — APPROVED** [review]

**Pull request merged**
